### PR TITLE
Fix forecast mixing temp low/high from different days

### PR DESCRIPTION
**Pull request by luiscantero**

### CODE REVIEW

**Comment by LoveBootCaptain** [comment]
Hi @luiscantero,

what's the intention to just add 0.5 degrees to the current temp delivered by the api?
also why changing the 3 day forcast from "the next 3 upcoming days" to "today and the next 2 upcoming days"  the information from the forecast for the current day is mostly redundant to the current weather data.

I will close this PR. If anyone want's to configure it in that way it is fine for me, but not in a pull request. you can easily create your own fork and add this features in your fork. ;)

hope thats fine for you.

kind regards and thx for your interest an participation in this project

**Comment by luiscantero** [comment]
Hi,

Thanks for your time.

By adding 0.5 I wanted to round the temp up, but I forgot to use ceil in the version that I pushed. Nobody needs a temperature reading with 1/100 precision, it just clutters the UI, but I agree, it's a matter of taste :)

But the more important issue is that there are some inconsistencies here:
image

Feel free to fix them yourself. Many thanks for your nice work!

**Comment by LoveBootCaptain** [comment]
Hi @luiscantero,

you are RIGHT... I mixed some numbers there and didn't get it in the first place...
thats a bug :D i will fix that asap ;)

to your conversion... i get your point why you wanted to do that. but you are already converting it to a full number by doing:

`temp_out_string = str(int(current_forecast['temp'])) + '°C'`

`int` will be rounded up, if it's >= x.5

**Comment by LoveBootCaptain** [comment]
or one other option @luiscantero:

would you consider removing the conversion of the current temp string?

than i would straight merge your pull request / bugfix for the forecast asap.

what would you say? good compromise?

**Comment by LoveBootCaptain** [comment]
fixed in https://github.com/LoveBootCaptain/WeatherPi_TFT/commit/d657a1c687ef535f3a763084eae478b6088915be

**Pull request closed without merging**
